### ISSUE TITLE
Support field mapping for packages/messages having different names?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros1_bridge#134]
Currently the docs example for field mapping rules gives the following example:
```
-
  ros1_package_name: 'pkg_name'
  ros1_message_name: 'msg_name'
  ros2_package_name: 'pkg_name'
  ros2_message_name: 'msg_name'
  fields_1_to_2:
    foo: 'foo'
    ros1_bar: 'ros2_bar'
```

Is it intentional that we do not support defining mapping with either different pkg_name, different message names or both ?

In other words should the following be valid?

```
-
  ros1_package_name: 'ros1_pkg_name'
  ros1_message_name: 'ros1_msg_name'
  ros2_package_name: 'ros2_pkg_name'
  ros2_message_name: 'ros2_msg_name'
  fields_1_to_2:
    foo: 'foo'
    ros1_bar: 'ros2_bar'
```
