### ISSUE TITLE
failed to create 2to1 bridge for topic '/rosout' with ROS 2 type

### ISSUE THREAD

**Issue by qingmingjie** [ros2/ros1_bridge#159]
When excute "ros2 run ros1_bridge dynamic_bridge", terminal diaplay "failed to create 2to1 bridge for topic '/rosout' with ROS 2 type 'rcl_interfaces/Log' and ROS 1 type 'rosgraph_msgs/Log': No template specialization for the pair".

**Comment by dirk-thomas** [comment]
@nburek Since you added the `rcl_interfaces/Log` message in ros2/rcl_interfaces#53 can you maybe provide a pull request to also add a custom mapping file for it?

**Comment by nburek** [comment]
Yes, I've added it to my team's backlog and we will schedule someone to start working on it next week. 

In the mean time, if you add the command line argument `__log_disable_rosout:=true` to the command line arguments when using `ros2 run` it will disable the rosout feature and the nodes should not create  the topic. This may be hard to verify with the command line tools as they spin up their own node to communicate with the service. I'm not sure if there is an easy way to include the disable flag when running that.

**Comment by juanrh** [comment]
Hi @dirk-thomas, I'm taking a look to this. I'm trying to use a mapping file as suggested, but I have the problem that for obtaining a value for the field `stamp` of [`rcl_interfaces/Log`](https://github.com/ros2/rcl_interfaces/blob/master/rcl_interfaces/msg/Log.msg) from a [`rosgraph_msgs/Log`](https://docs.ros.org/kinetic/api/rosgraph_msgs/html/msg/Log.html) message I need to access the value `stamp` nested in the field `header` with type [`std_msgs/Header`](https://docs.ros.org/kinetic/api/std_msgs/html/msg/Header.html). So I'd have to use a mapping file like:

```yaml
-
  ros1_package_name: 'rosgraph_msgs'
  ros1_message_name: 'Log'
  ros2_package_name: 'rcl_interfaces'
  ros2_message_name: 'Log'
  fields_1_to_2:
    header.stamp: 'stamp'
    level: 'level'
    name: 'name'
    msg: 'msg'
    file: 'file'
    function: 'function'
    line: 'line'
```

which is not valid because as far as I know projections cannot be specified in the mapping rule files. So this file is ignored during the build of `ros1_bridge install` with a message "A manual mapping refers to an invalid field 'header.stamp' in the ROS 1 message 'rosgraph_msgs/Log'". 

Is there a way to express these kind of projections for mapping files? Do you think I should do this with C++ instead, by adding another factory to [`builtin_interfaces_factories.hpp`](https://github.com/ros2/ros1_bridge/blob/master/include/ros1_bridge/builtin_interfaces_factories.hpp) instead? Any idea would be much appreciated.

Thanks
